; https://github.com/NoiseByNorthwest/php-spx?tab=readme-ov-file#configuration
extension = spx.so

spx.http_enabled = 1
spx.http_profiling_enabled = 1
spx.http_ip_whitelist = '*'
spx.http_trusted_proxies = '*'
spx.http_key = 'dev'
