" Enable filetype plugins
filetype plugin indent on

" Enable syntax highlighting
syntax enable

" Change mapleader
let mapleader=" "
let g:mapleader=" "

set nocompatible        " Make vim more useful
set nu relativenumber   " Enable line numbers
"set cursorline          " Highlight line under the cursor
set ruler               " Show cursor position
set colorcolumn=80,100,120

"hi! Comment ctermfg=240
hi! CursorLineNr ctermfg=255
hi! LineNr ctermfg=240
hi! StatusLine ctermbg=238
hi! Visual ctermbg=238

let s:vim_home_dir=$HOME.'/.vim'

if !isdirectory(s:vim_home_dir.'/autoload')
  call mkdir(s:vim_home_dir.'/autoload', 'p')
endif

if !filereadable(s:vim_home_dir.'/autoload/plug.vim')
  let s:plug_download_url='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  call system('curl -fLo '.s:vim_home_dir.'/autoload/plug.vim --create-dirs '.s:plug_download_url)

  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

function s:plug_download_dir()
  if !empty($LOCALAPPDATA)
    return $LOCALAPPDATA.'/vim-plug'
  endif

  if !empty($XDG_DATA_HOME)
    return $XDG_DATA_HOME.'/vim-plug'
  endif

  return $HOME.'/.local/share/vim-plug'
endfunction

let s:plug_home_dir=s:plug_download_dir()

if !isdirectory(s:plug_home_dir)
  call mkdir(s:plug_home_dir, 'p')
endif

call plug#begin(s:plug_home_dir)

Plug 'editorconfig/editorconfig-vim'
Plug 'wakatime/vim-wakatime'

call plug#end()

let s:vim_cache_dir=$HOME.'/.cache/vim'

" Persistent Undo
if !isdirectory(s:vim_cache_dir.'/undo')
  call mkdir(s:vim_cache_dir.'/undo', 'p')
endif

set undofile
set undolevels=10000
set undodir=s:vim_cache_dir.'/undo'

" Swap
if !isdirectory(s:vim_cache_dir.'/swap')
  call mkdir(s:vim_cache_dir.'/swap', 'p')
endif

set swapfile
set directory^=s:vim_cache_dir.'/swap//'

" =====

set conceallevel=3
set updatetime=50

"set laststatus=2
"set noshowmode     " Hide the current mode

set noerrorbells   " Disable error bells
set visualbell     " Use visual bell instead of audible bell (annnnnoying)
"set nojoinspaces   " Only insert single space after a '.', '?' and '!' with a join command
set nostartofline  " Don't reset cursor to start of line when moving around

set mouse=a   " Enable moouse in all in all modes
set report=0  " Show all command reports
set confirm   " Confirm before exit if file has changed
set nohidden  " Close the buffer when tab is closed
set nowrap    " Do not wrap lines

set encoding=utf-8 nobomb  " BOM often causes trouble
set ffs=unix,dos,mac       " Use Unix as the standard file type

" Completion
if has('wildmenu')
  set wildmenu
  set wildmode=longest:full,full
  set wildchar=<TAB>

  set wildignore+=*/vendor/*,*/node_modules/*,*/.git/*,*/.DS_Store
endif

set completeopt=menu,menuone,noselect
set showfulltag  " Show full completion tags

" Indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Auto/Smart/Copy indent from last line when starting new line
set autoindent smartindent copyindent
set backspace=indent,eol,start

" Searches
set hlsearch    " Highlight searches
set incsearch   " Highlight dynamically as pattern is typed
set ignorecase  " Ignore case of searches
set smartcase   " Ignore 'ignorecase' if search patter contains uppercase characters
set wrapscan    " Searches wrap around end of file

" Keep cursor in the middle while in search results
nmap n nzzzv  " Previeous search result
nmap N Nzzzv  " Next search result

nnoremap <Esc><Esc> :noh<CR> " Double <esc> to clear search highlight

" Window splitting
set splitbelow  " New window goes below
set splitright  " New windows goes right

" Buffers navigation
nnoremap <Tab> :bnext<CR>       " Next Buffer
nnoremap <S-Tab> :bprevious<CR> " Previous Buffer

" Move lines - use ALT+J/K to move line up and down
nnoremap <A-j> :m .+1<CR>==         " Move lines down
nnoremap <A-k> :m .-2<CR>==         " Move lines up
inoremap <A-j> <Esc>:m .+1<CR>==gi  " Move lines down
inoremap <A-k> <Esc>:m .-2<CR>==gi  " Move lines up
vnoremap <A-j> :m '>+1<CR>gv=gv     " Move lines down
vnoremap <A-k> :m '<-2<CR>gv=gv     " Move lines up
