; https://php.net/error-reporting
error_reporting = E_ALL & ~E_DEPRECATED

; https://php.net/display-errors
display_errors = On

; https://php.net/display-startup-errors
display_startup_errors = On

; Max memory per instance
memory_limit = 2048M
; memory_limit = -1

;The maximum size of an uploaded file.
; https://php.net/upload-max-filesize
upload_max_filesize = 32M

; Maximum number of files that can be uploaded via a single request
max_file_uploads = 20

; Sets max size of post data allowed.
; Changes to this will also need to be reflected in Nginx with client_max_body_size
; This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize
; https://php.net/post-max-size
post_max_size = 32M

; Name for user-defined php.ini (.htaccess) files. Default is ".user.ini"
; To disable this feature set this option to an empty value
;user_ini.filename = ".user.ini"

[mail function]
; For Win32 only.
; https://php.net/smtp
; SMTP = localhost
; https://php.net/smtp-port
; smtp_port = 25

; For Win32 only.
; https://php.net/sendmail-from
;sendmail_from = me@example.com

; For Unix only.  You may supply arguments as well (default: "sendmail -t -i").
; https://php.net/sendmail-path
;sendmail_path =
