[[rule]]
decision = "allow"
priority = 950
toolName = "activate_skill"
modes = [ "plan", "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "enter_plan_mode"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "exit_plan_mode"
modes = [ "plan" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [
  "act",
  "asdf",
  "bun",
  "composer",
  "devcontainer",
  "docker",
  "gh",
  "git",
  "npm",
  "pnpm"
]
modes = [ "plan", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "cat", "chmod", "grep", "ls", "man" ]
allowRedirection = true
modes = [ "plan", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "sequentialthinking"
mcpName = "mcp-server-sequential-thinking"
modes = [ "plan", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "echo"
mcpName = "mcp-server-everything"
modes = [ "autoEdit", "yolo" ]
