[[rule]]
decision = "allow"
priority = 950
toolName = "activate_skill"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "act", "asdf", "bun", "composer", "devcontainer", "docker", "gh", "git", "npm", "pnpm" ]
modes = [ "plan", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "cat", "chmod", "grep", "ls", "man" ]
allowRedirection = true
modes = [ "plan", "autoEdit", "yolo" ]
