"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[aws]
disabled = true

[gcloud]
disabled = true
